---
 # SEI growth
 alpha_SEI: 0.5      # [-]        SEI charge transfer coefficient
 c_EC_bulk: 4541     # mol/m3     Concentration of EC in bulk electrolyte
 delta_SEI_0: 5.0e-9 # m          Initial SEI thickness
 V_sei: 9.585e-5     # m3/mol     SEI molar volume
 L_n: 80.0e-6        # m          Negative electrode thickness
 k_SEI: 1.0e-11      # m/s        SEI kinetic rate constant
 D_SEI: 2.0e-16      # m2/s       SEI layer diffusivity
 R_n: 20.0e-6        # m          Anode particle radius
 epsilon_n: 0.7      # [-]        Anode solid material fraction
 a_SEI: 105000       # 1/m        Anode specific surface area
 A_n: 0.100          # m2         Anode active area
 U_SEI: 0.4          # V          SEI equilibrium reaction potential

 # Expansion
 c0: 15
 c1: 0.00166667
 c2: 0.00166667

 # Overpotential
 R0p: 0.0205
 R0n: 0.0205
 R1p: 0.079
 R1n: 0.079
 C1p: 76000
 C1n: 76000

 # eOCP
 Cn: 6 # Ah
 Cp: 6 # Ah
 theta_n: 0.0
 theta_p: 1.0
